added functionality to handle RGBA, i.e. 4 channels and related modif…
YavorGIvanov/sam.cpp pull request #20
Opened 2023-09-15 08:09 UTC by bhavuk2002

thanks. im new to open source, first i read about image channels and got the understanding what they are, here basically we have to add ALPHA in loading image, we are currently missing that, thats why errors are getting generaated. I read documentation for stbi_load and have modified the code base accordingly and handled error accordingly. 

Can someone test it?

2023-09-15 08:12 UTC, YavorGIvanov requested changes
There a couple of places in the example where the number of channels is assumed to be 3. This surely won't work. You will have to propagate the number of channels as a member variable in the sam_image_u8 and use it later.

You may need some help with this.

2023-09-15 08:18 UTC, bhavuk2002 commented
oh ya i was thinking of editing sam_image_u8 but neglected it. will do surely, and update sam_image_u8.

2023-09-15 08:19 UTC, bhavuk2002 commented
one more thing apart from that logic for load_image_from_file is fine?

2023-09-15 08:30 UTC, bhavuk2002 commented
![image](https://github.com/YavorGIvanov/sam.cpp/assets/63869440/ac66e587-6a81-49e5-8405-4ea8dedb9cc3)
in the code base here at line number 340 we are resizing the mask. Do we need to use 4 channels here or 3 are enough for 4 channels too? Apart from this function in main.cpp / examples, there is no hard coding of number of channels left.

2023-09-16 04:01 UTC, bhavuk2002 commented
can you please elaborate, how can i work forward on this?

2023-09-17 13:16 UTC, YavorGIvanov commented
Should a png image with alpha channel and test that the sample works. I will try to do that today or tomorrow and look more carefully through your change.

2023-09-17 15:41 UTC, bhavuk2002 commented
uhm png image doesnt support alpha channel.

2023-09-17 19:18 UTC, YavorGIvanov commented
https://www.w3.org/TR/PNG-DataRep.html Section 2.4

2023-09-17 19:27 UTC, bhavuk2002 commented
Okay i was wrong, now what changes should i make and where?

2023-09-20 15:31 UTC, bhavuk2002 commented
any info or update?

2023-09-23 16:22 UTC, bhavuk2002 commented
any update?

2023-09-28 19:03 UTC, YavorGIvanov commented on examples/main.cpp
> +    int ok = stbi_info(filename, &nx, &ny, &nc);
This doesn't compile. filename is undefined. You also added a couple of trailing tabs below.

2023-09-28 19:03 UTC, YavorGIvanov commented on examples/main.cpp
> +    if(ok == 0) return 0;
space after if

2023-10-05 11:49 UTC, closed without merging